/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Calcolatrice;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.EmptyStackException;
import java.util.List;
import java.util.NoSuchElementException;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.CoreStack;
import model.ComplexNumber;

public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    Calcolatrice calcolatrice;
    CoreStack coreStack;
    List<ComplexNumber> numList;
    DefaultListModel model;

    public Gui() {
        initComponents();
    }

    public Gui(Calcolatrice calcolatrice, CoreStack coreStack) {
        initComponents();
        this.calcolatrice = calcolatrice;
        this.coreStack = coreStack;
        this.numList = new ArrayList<>();
        this.model = new DefaultListModel();

        buttonInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/info.png"))); // NOI18N

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        buttonSum = new javax.swing.JButton();
        buttonDiff = new javax.swing.JButton();
        buttonProd = new javax.swing.JButton();
        buttonDiv = new javax.swing.JButton();
        buttonSqr = new javax.swing.JButton();
        buttonInv = new javax.swing.JButton();
        textInsertNumber = new javax.swing.JTextField();
        buttonInsert = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        buttonDup = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        buttonSwap = new javax.swing.JButton();
        buttonDrop = new javax.swing.JButton();
        buttonOver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listComplexNumbers = new javax.swing.JList<>();
        labelListTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelTitle2 = new javax.swing.JLabel();
        textInsertOperations = new javax.swing.JTextField();
        buttonInfo = new javax.swing.JButton();
        buttonInsertFunction = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(502, 400));
        setResizable(false);

        buttonSum.setText("Somma");
        buttonSum.setMaximumSize(new java.awt.Dimension(100, 25));
        buttonSum.setMinimumSize(new java.awt.Dimension(100, 25));
        buttonSum.setPreferredSize(new java.awt.Dimension(100, 25));
        buttonSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSumActionPerformed(evt);
            }
        });

        buttonDiff.setText("Differenza");
        buttonDiff.setMaximumSize(new java.awt.Dimension(100, 25));
        buttonDiff.setMinimumSize(new java.awt.Dimension(100, 25));
        buttonDiff.setPreferredSize(new java.awt.Dimension(100, 25));
        buttonDiff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDiffActionPerformed(evt);
            }
        });

        buttonProd.setText("Prodotto");
        buttonProd.setMaximumSize(new java.awt.Dimension(100, 25));
        buttonProd.setMinimumSize(new java.awt.Dimension(100, 25));
        buttonProd.setPreferredSize(new java.awt.Dimension(100, 25));
        buttonProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProdActionPerformed(evt);
            }
        });

        buttonDiv.setText("Divisione");
        buttonDiv.setMaximumSize(new java.awt.Dimension(100, 25));
        buttonDiv.setMinimumSize(new java.awt.Dimension(100, 25));
        buttonDiv.setPreferredSize(new java.awt.Dimension(100, 25));
        buttonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivActionPerformed(evt);
            }
        });

        buttonSqr.setText("Radice Quadrata");
        buttonSqr.setMaximumSize(new java.awt.Dimension(125, 25));
        buttonSqr.setMinimumSize(new java.awt.Dimension(125, 25));
        buttonSqr.setPreferredSize(new java.awt.Dimension(125, 25));
        buttonSqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSqrActionPerformed(evt);
            }
        });

        buttonInv.setText("Inversione Segno");
        buttonInv.setMaximumSize(new java.awt.Dimension(125, 25));
        buttonInv.setMinimumSize(new java.awt.Dimension(125, 25));
        buttonInv.setPreferredSize(new java.awt.Dimension(125, 25));
        buttonInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInvActionPerformed(evt);
            }
        });

        textInsertNumber.setMaximumSize(new java.awt.Dimension(60, 25));
        textInsertNumber.setMinimumSize(new java.awt.Dimension(60, 25));
        textInsertNumber.setPreferredSize(new java.awt.Dimension(60, 25));
        textInsertNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textInsertNumberActionPerformed(evt);
            }
        });

        buttonInsert.setText("Inserisci");
        buttonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertActionPerformed(evt);
            }
        });

        labelTitle.setText("Calcolatrice Con Numeri Complessi");

        buttonDup.setText("Dup");
        buttonDup.setMaximumSize(new java.awt.Dimension(65, 25));
        buttonDup.setMinimumSize(new java.awt.Dimension(65, 25));
        buttonDup.setPreferredSize(new java.awt.Dimension(65, 25));
        buttonDup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDupActionPerformed(evt);
            }
        });

        buttonClear.setText("Clear");
        buttonClear.setMaximumSize(new java.awt.Dimension(65, 25));
        buttonClear.setMinimumSize(new java.awt.Dimension(65, 25));
        buttonClear.setPreferredSize(new java.awt.Dimension(65, 25));
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        buttonSwap.setText("Swap");
        buttonSwap.setMaximumSize(new java.awt.Dimension(65, 25));
        buttonSwap.setMinimumSize(new java.awt.Dimension(65, 25));
        buttonSwap.setPreferredSize(new java.awt.Dimension(65, 25));
        buttonSwap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSwapActionPerformed(evt);
            }
        });

        buttonDrop.setText("Drop");
        buttonDrop.setMaximumSize(new java.awt.Dimension(65, 25));
        buttonDrop.setMinimumSize(new java.awt.Dimension(65, 25));
        buttonDrop.setPreferredSize(new java.awt.Dimension(65, 25));
        buttonDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDropActionPerformed(evt);
            }
        });

        buttonOver.setText("Over");
        buttonOver.setMaximumSize(new java.awt.Dimension(65, 25));
        buttonOver.setMinimumSize(new java.awt.Dimension(65, 25));
        buttonOver.setPreferredSize(new java.awt.Dimension(65, 25));
        buttonOver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(labelTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(textInsertNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonInsert))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buttonSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buttonDiff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(buttonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonSqr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonInv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonDup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonSwap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonOver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textInsertNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInsert))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSqr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSwap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listComplexNumbers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listComplexNumbers);

        labelListTitle.setText("Lista Elementi Stack");

        labelTitle2.setText("Inserisci la sequenza di operazioni:");

        textInsertOperations.setMaximumSize(new java.awt.Dimension(60, 25));
        textInsertOperations.setMinimumSize(new java.awt.Dimension(60, 25));
        textInsertOperations.setPreferredSize(new java.awt.Dimension(60, 25));
        textInsertOperations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textInsertOperationsActionPerformed(evt);
            }
        });

        buttonInfo.setMaximumSize(new java.awt.Dimension(25, 25));
        buttonInfo.setMinimumSize(new java.awt.Dimension(25, 25));
        buttonInfo.setPreferredSize(new java.awt.Dimension(25, 25));
        buttonInfo.setVerifyInputWhenFocusTarget(false);
        buttonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInfoActionPerformed(evt);
            }
        });

        buttonInsertFunction.setText("Inserisci Funzione");
        buttonInsertFunction.setMaximumSize(new java.awt.Dimension(150, 25));
        buttonInsertFunction.setMinimumSize(new java.awt.Dimension(150, 25));
        buttonInsertFunction.setPreferredSize(new java.awt.Dimension(150, 25));
        buttonInsertFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertFunctionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textInsertOperations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(labelTitle2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonInsertFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelTitle2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textInsertOperations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonInsertFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelListTitle))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelListTitle)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo richiamato quando viene premuto il pulsante "Somma"
     */
    private void buttonSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSumActionPerformed
        try {
            calcolatrice.stackSum();
        } catch (EmptyStackException e) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Non ci sono abbastanza elementi nello stack\n"
                    + "per effettuare l'operazione somma");

            textInsertNumber.setText("");
            return;
        }

        updateModel();
    }//GEN-LAST:event_buttonSumActionPerformed
    /**
     * Metodo richiamato quando viene premuto il pulsante "Differenza"
     */
    private void buttonDiffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDiffActionPerformed
        try {
            calcolatrice.stackDiff();
        } catch (EmptyStackException e) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Non ci sono abbastanza elementi nello stack\n"
                    + "per effettuare l'operazione differenza");

            textInsertNumber.setText("");
            return;
        }

        updateModel();

    }//GEN-LAST:event_buttonDiffActionPerformed
    /**
     * Metodo richiamato quando viene premuto il pulsante "Prodotto"
     */
    private void buttonProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProdActionPerformed
       try {
              calcolatrice.stackProd();
        } catch (EmptyStackException e) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Non ci sono abbastanza elementi nello stack\n"
                    + "per effettuare l'operazione prodotto");

            textInsertNumber.setText("");
            return;
        }

        updateModel();
    }//GEN-LAST:event_buttonProdActionPerformed
    /**
     * Metodo richiamato quando viene premuto il pulsante "Divisione"
     */
    private void buttonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivActionPerformed
         try {
               calcolatrice.stackDiv();
        } catch (EmptyStackException e) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Non ci sono abbastanza elementi nello stack\n"
                    + "per effettuare l'operazione divisione");

            textInsertNumber.setText("");
            return;
        }
        updateModel();
    }//GEN-LAST:event_buttonDivActionPerformed
    /**
     * Metodo richiamato quando viene premuto il pulsante "Radice Quadrata"
     */
    private void buttonSqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSqrActionPerformed
         try {
               calcolatrice.stackSqr();
        } catch (EmptyStackException e) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Non ci sono abbastanza elementi nello stack\n"
                    + "per effettuare l'operazione sqrt");

            textInsertNumber.setText("");
            return;
        }
        updateModel();
    }//GEN-LAST:event_buttonSqrActionPerformed
    /**
     * Metodo richiamato quando viene premuto il pulsante "Inversione di Segno"
     */
    private void buttonInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInvActionPerformed
        try {
                calcolatrice.stackInv();
        } catch (EmptyStackException e) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Non ci sono abbastanza elementi nello stack\n"
                    + "per effettuare l'operazione di inversione");

            textInsertNumber.setText("");
            return;
        }
       
        updateModel();
    }//GEN-LAST:event_buttonInvActionPerformed
    /**
     * Metodo richiamato quando viene premuto il pulsante "Inserisci" Questo
     * metodo richiama il metodo stackInv() per l'inserimento nello stack
     */
    private void buttonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertActionPerformed
        // TODO add your handling code here:
        double real = 0, complex = 0;
        String realPart = null;
        String complexPart = null;

        String expression = textInsertNumber.getText();

        if (isOperation(expression)) {
            System.out.println("FUNZIONA!");
            try {
                calcolatrice.executeOperation(expression);
            } catch (NoSuchElementException e) {
                JFrame jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "La variabile non è inizializzata");

                textInsertNumber.setText("");
                return;
            }
            textInsertNumber.setText("");
            updateModel();

            return;
        } else if (isExpression(expression)) {
            if ((expression.lastIndexOf("+") == -1) || (expression.lastIndexOf("+") == 0)) {
                realPart = expression.substring(0, expression.lastIndexOf("-"));
                complexPart = expression.substring(expression.lastIndexOf("-") + 1, expression.lastIndexOf("i"));
            } else {
                realPart = expression.substring(0, expression.lastIndexOf("+"));
                complexPart = expression.substring(expression.lastIndexOf("+") + 1, expression.lastIndexOf("i"));
            }
        } else if (isReal(expression)) {
            realPart = expression.substring(0, expression.lastIndexOf(""));
            complexPart = "0";
        } else if (isComplex(expression)) {
            realPart = "0";
            complexPart = expression.substring(0, expression.lastIndexOf("i"));
        } else {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Devi inserire l'espressione nella forma corretta!");

            textInsertNumber.setText("");
            return;
        }

        real = Double.parseDouble(realPart);
        complex = Double.parseDouble(complexPart);

        textInsertNumber.setText("");
        calcolatrice.creatComplexNumber(real, complex);
        updateModel();

    }//GEN-LAST:event_buttonInsertActionPerformed

    private void textInsertNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textInsertNumberActionPerformed
        buttonInsertActionPerformed(evt);
    }//GEN-LAST:event_textInsertNumberActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        coreStack.clear();
        updateModel();
    }//GEN-LAST:event_buttonClearActionPerformed

    private void buttonDupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDupActionPerformed
        try {
            coreStack.duplicate();
        } catch (NoSuchElementException e) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Attenzione, lo Stack è vuoto!");
        }

        updateModel();
    }//GEN-LAST:event_buttonDupActionPerformed

    private void buttonSwapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSwapActionPerformed
        try {
            coreStack.swap();
        } catch (NoSuchElementException e) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Gli elementi nello Stack non sono sufficienti per l'operazione di Swap");
        }
        updateModel();
    }//GEN-LAST:event_buttonSwapActionPerformed

    private void buttonDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDropActionPerformed
        try {
            coreStack.drop();
        } catch (NoSuchElementException e) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Attenzione, lo Stack è vuoto!");
        }
        updateModel();
    }//GEN-LAST:event_buttonDropActionPerformed

    private void buttonOverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOverActionPerformed
        try {
            coreStack.over();
        } catch (NoSuchElementException e) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Gli elementi nello Stack non sono sufficienti per l'operazione di Over");
        }
        updateModel();
    }//GEN-LAST:event_buttonOverActionPerformed

    private void textInsertOperationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textInsertOperationsActionPerformed
        buttonInsertFunctionActionPerformed(evt);
    }//GEN-LAST:event_textInsertOperationsActionPerformed

    private void buttonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInfoActionPerformed
        try {
            coreStack.over();
        } catch (NoSuchElementException e) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Inserisci il nome della funzione in questo modo [funzione]\n"
                    + "Inserisci le operazioni in questo modo: [op1 op2 op3 push(x+yi)]\n"
                    + "Per eseguire una funzione basta inserire il nome della funzione e premere invio");
        }
    }//GEN-LAST:event_buttonInfoActionPerformed

    private void buttonInsertFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertFunctionActionPerformed
        String operations = textInsertOperations.getText();
        calcolatrice.Function(operations);
    }//GEN-LAST:event_buttonInsertFunctionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    //Useful Methods
    /**
     * Metodo che ritorna True se in String sono presenti solo caratteri
     * numerici, che possono essere anche seguiti da un simbolo "-", False
     * altrimenti
     *
     * @param String stringa in input
     * @return boolean (True o False)
     */
    public static boolean isNumeric(String str) {
        return str.matches("-?\\d+(\\.\\d+)?");  //match a number with optional '-' and decimal.
    }

    /**
     * Metodo che ritorna True se in String sono presenti solo caratteri
     * numerici complessi nella forma cartesiana
     *
     * @param String stringa in input
     * @return boolean (True o False)
     */
    public static boolean isExpression(String str) {
        return str.matches("[-+]?\\d+(\\.\\d+)?[-+]+\\d+(\\.\\d+)?i+");
    }

    /**
     * Metodo che ritorna True se in String sono presenti solo caratteri
     * numerici eventualmente seguiti da un segno
     *
     * @param String stringa in input
     * @return boolean (True o False)
     */
    public static boolean isReal(String str) {
        return str.matches("[-+]?\\d+(\\.\\d+)?");
    }

    /**
     * Metodo che ritorna True se in String sono presenti solo caratteri
     * numerici seguiti dal simbolo "i" ed eventualmente seguiti da un segno
     *
     * @param String stringa in input
     * @return boolean (True o False)
     */
    public static boolean isComplex(String str) {
        return str.matches("[-+]?\\d+(\\.\\d+)?i+");
    }

    /**
     * Metodo che ritorna True se in String sono presenti solo caratteri
     * numerici eventualmente seguiti da un segno
     *
     * @param String stringa in input
     * @return boolean (True o False)
     */
    public static boolean isOperation(String str) {
        return str.matches("[-+<>][a-z]");
    }

    /**
     * Metodo necessario per aggiornare il model del component
     * listComplexNumbers
     */
    public void updateModel() {
        numList = coreStack.getSubList();
        model.clear();
        for (int i = 0; i < numList.size(); i++) {
            ComplexNumber element = numList.get(i);
            model.addElement(element);
        }
        listComplexNumbers.setModel(model);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDiff;
    private javax.swing.JButton buttonDiv;
    private javax.swing.JButton buttonDrop;
    private javax.swing.JButton buttonDup;
    private javax.swing.JButton buttonInfo;
    private javax.swing.JButton buttonInsert;
    private javax.swing.JButton buttonInsertFunction;
    private javax.swing.JButton buttonInv;
    private javax.swing.JButton buttonOver;
    private javax.swing.JButton buttonProd;
    private javax.swing.JButton buttonSqr;
    private javax.swing.JButton buttonSum;
    private javax.swing.JButton buttonSwap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelListTitle;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTitle2;
    private javax.swing.JList<String> listComplexNumbers;
    private javax.swing.JTextField textInsertNumber;
    private javax.swing.JTextField textInsertOperations;
    // End of variables declaration//GEN-END:variables
}
