/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Calcolatrice;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.CoreStack;
import model.NumeroComplesso;

/**
 *
 * @author gigi9
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    Calcolatrice calcolatrice;
    CoreStack coreStack;
    List<NumeroComplesso> numList;
    DefaultListModel model;

    public Gui() {
        initComponents();
    }

    public Gui(Calcolatrice calcolatrice, CoreStack coreStack) {
        initComponents();
        this.calcolatrice = calcolatrice;
        this.coreStack = coreStack;
        this.numList = new ArrayList<>();
        this.model = new DefaultListModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonSum = new javax.swing.JButton();
        buttonDiff = new javax.swing.JButton();
        buttonProd = new javax.swing.JButton();
        buttonDiv = new javax.swing.JButton();
        buttonSqr = new javax.swing.JButton();
        buttonInv = new javax.swing.JButton();
        labelRealPart = new javax.swing.JLabel();
        labelComplexPart = new javax.swing.JLabel();
        textRealPart = new javax.swing.JTextField();
        textComplexPart = new javax.swing.JTextField();
        buttonInsert = new javax.swing.JButton();
        labelPlus = new javax.swing.JLabel();
        labelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listComplexNumbers = new javax.swing.JList<>();
        labelListTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonSum.setText("Somma");
        buttonSum.setMaximumSize(new java.awt.Dimension(85, 25));
        buttonSum.setMinimumSize(new java.awt.Dimension(85, 25));
        buttonSum.setPreferredSize(new java.awt.Dimension(85, 25));
        buttonSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSumActionPerformed(evt);
            }
        });

        buttonDiff.setText("Differenza");
        buttonDiff.setMaximumSize(new java.awt.Dimension(85, 25));
        buttonDiff.setMinimumSize(new java.awt.Dimension(85, 25));
        buttonDiff.setPreferredSize(new java.awt.Dimension(85, 25));
        buttonDiff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDiffActionPerformed(evt);
            }
        });

        buttonProd.setText("Prodotto");
        buttonProd.setMaximumSize(new java.awt.Dimension(85, 25));
        buttonProd.setMinimumSize(new java.awt.Dimension(85, 25));
        buttonProd.setPreferredSize(new java.awt.Dimension(85, 25));
        buttonProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProdActionPerformed(evt);
            }
        });

        buttonDiv.setText("Divisione");
        buttonDiv.setMaximumSize(new java.awt.Dimension(85, 25));
        buttonDiv.setMinimumSize(new java.awt.Dimension(85, 25));
        buttonDiv.setPreferredSize(new java.awt.Dimension(85, 25));
        buttonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivActionPerformed(evt);
            }
        });

        buttonSqr.setText("Radice Quadrata");
        buttonSqr.setMaximumSize(new java.awt.Dimension(125, 25));
        buttonSqr.setMinimumSize(new java.awt.Dimension(125, 25));
        buttonSqr.setPreferredSize(new java.awt.Dimension(125, 25));
        buttonSqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSqrActionPerformed(evt);
            }
        });

        buttonInv.setText("Inversione Segno");
        buttonInv.setMaximumSize(new java.awt.Dimension(125, 25));
        buttonInv.setMinimumSize(new java.awt.Dimension(125, 25));
        buttonInv.setPreferredSize(new java.awt.Dimension(125, 25));
        buttonInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInvActionPerformed(evt);
            }
        });

        labelRealPart.setText("Parte Reale");

        labelComplexPart.setText("Parte Immaginaria");

        textRealPart.setMaximumSize(new java.awt.Dimension(60, 25));
        textRealPart.setMinimumSize(new java.awt.Dimension(60, 25));
        textRealPart.setPreferredSize(new java.awt.Dimension(60, 25));

        textComplexPart.setMaximumSize(new java.awt.Dimension(60, 25));
        textComplexPart.setMinimumSize(new java.awt.Dimension(60, 25));
        textComplexPart.setPreferredSize(new java.awt.Dimension(60, 25));

        buttonInsert.setText("Inserisci");
        buttonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertActionPerformed(evt);
            }
        });

        labelPlus.setText("+");

        labelTitle.setText("Calcolatrice Con Numeri Complessi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelTitle)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelRealPart, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(textRealPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelPlus)
                                        .addGap(8, 8, 8)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(labelComplexPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(textComplexPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonInsert)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonDiff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSqr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRealPart)
                    .addComponent(labelComplexPart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRealPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textComplexPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInsert)
                    .addComponent(labelPlus))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSqr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        listComplexNumbers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listComplexNumbers);

        labelListTitle.setText("Lista Elementi Stack");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelListTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelListTitle)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo richiamato quando viene premuto il pulsante "Somma"
     */
    private void buttonSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSumActionPerformed
        // TODO add your handling code here:
        calcolatrice.stackSum();
    }//GEN-LAST:event_buttonSumActionPerformed
    /**
     * Metodo richiamato quando viene premuto il pulsante "Differenza"
     */
    private void buttonDiffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDiffActionPerformed
        // TODO add your handling code here:
        calcolatrice.stackDiff();
    }//GEN-LAST:event_buttonDiffActionPerformed
    /**
     * Metodo richiamato quando viene premuto il pulsante "Prodotto"
     */
    private void buttonProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProdActionPerformed
        // TODO add your handling code here:
        calcolatrice.stackProd();
    }//GEN-LAST:event_buttonProdActionPerformed
    /**
     * Metodo richiamato quando viene premuto il pulsante "Divisione"
     */
    private void buttonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivActionPerformed
        // TODO add your handling code here:
        calcolatrice.stackDiv();
    }//GEN-LAST:event_buttonDivActionPerformed
    /**
     * Metodo richiamato quando viene premuto il pulsante "Radice Quadrata"
     */
    private void buttonSqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSqrActionPerformed
        // TODO add your handling code here:
        calcolatrice.stackSqr();
    }//GEN-LAST:event_buttonSqrActionPerformed
    /**
     * Metodo richiamato quando viene premuto il pulsante "Inversione di Segno"
     */
    private void buttonInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInvActionPerformed
        // TODO add your handling code here:
        calcolatrice.stackInv();
    }//GEN-LAST:event_buttonInvActionPerformed
    /**
     * Metodo richiamato quando viene premuto il pulsante "Inserisci" Questo
     * metodo richiama il metodo stackInv() per l'inserimento nello stack
     */
    private void buttonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertActionPerformed
        // TODO add your handling code here:
        String realPart = textRealPart.getText();
        String complexPart = textComplexPart.getText();

        if (isNumeric(realPart) && isNumeric(complexPart)) {
            double real = Double.parseDouble(realPart);
            double img = Double.parseDouble(complexPart);

            calcolatrice.creatComplexNumber(real, img);
        } else {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "Devi inserire solo variabili numeriche!");
        }

        textRealPart.setText("");
        textComplexPart.setText("");
        
        numList = coreStack.getSubList();
        updateModel(model, numList);
        listComplexNumbers.setModel(model);
    }//GEN-LAST:event_buttonInsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    //Useful Methods
    /**
     * Metodo che ritorna True se in String sono presenti solo caratteri
     * numerici, False altrimenti
     * @param String stringa in input
     * @return boolean (True o False)
     */
    public static boolean isNumeric(String str) {
        return str.matches("-?\\d+(\\.\\d+)?");  //match a number with optional '-' and decimal.
    }
    
    public static void updateModel(DefaultListModel model, List<NumeroComplesso> list){
        model.clear();
        for (int i = 0; i<list.size(); i++) {
            NumeroComplesso element = list.get(i);
            model.addElement(element);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDiff;
    private javax.swing.JButton buttonDiv;
    private javax.swing.JButton buttonInsert;
    private javax.swing.JButton buttonInv;
    private javax.swing.JButton buttonProd;
    private javax.swing.JButton buttonSqr;
    private javax.swing.JButton buttonSum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelComplexPart;
    private javax.swing.JLabel labelListTitle;
    private javax.swing.JLabel labelPlus;
    private javax.swing.JLabel labelRealPart;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JList<String> listComplexNumbers;
    private javax.swing.JTextField textComplexPart;
    private javax.swing.JTextField textRealPart;
    // End of variables declaration//GEN-END:variables
}
